project:
  type: website

website:
  title: "ISSS608 VAA Project"
  navbar:
    left:
      - text: "Home"
        href: "index.html"
      - text: "Project Proposal"
        href: "project_proposal.html"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

