project:
  type: website
  
website:
  page-navigation: false
  title: "Visitor Arrivals Analysis"
  site-url: "https://isss608-vaa-project.netlify.app/"
  repo-url: "https://github.com/byebhai8/ISSS608-VAA-Project"
  page-footer:
    right: "ISSS608 VAA Project"
    left: "Group 10"
  sidebar:
    logo: "images/plane_logo_v2.png"
    pinned: true
    align: center
    tools: 
      - icon: "server"
        href: https://www.singstat.gov.sg/find-data/search-by-theme/industry/tourism/latest-data
        text: "Data Source"
      - icon: "display"
        href: https://byebhai8.shinyapps.io/ISSS608_VisitorArrivalAnalysis/
        text: "R Shiny Application"
      - icon: github
        href: https://github.com/byebhai8/ISSS608-VAA-Project
        text: "GitHub Repository"
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - text: "{{< bi house-fill >}} Home"
        href: index.qmd
      - text: "{{< bi text-paragraph >}} Project Overview"
        href: "project_overview.html"
      - text: "{{< bi file-earmark-richtext-fill >}} User Guide"
        href: "user_guide.html"
      - text: "{{< bi window-sidebar >}} Application"
        href: "application.html"
      - text: "{{< bi easel >}} Poster"
        href: "poster.html"
      - text: "{{< bi people-fill >}} About Us"
        href: about.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    page-layout: full

editor: visual

