project:
  type: website

website:
  title: "ISSS608 VAA Project"
  navbar:
    left:
      - text: "Project Proposal"
        href: "project_proposal.html"
    right: 
      - href: index.qmd
        text: Home
      - text: "Group 10"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

