project:
  type: website

website:
  title: "ISSS608 VAA Project"
  navbar:
    left:
      - text: "Project Proposal"
        href: "project_proposal.html"
      - text: "Working Script"
        href: "working_script.html"
      - text: "Application"
        href: "application.html"
    right: 
      - href: index.qmd
        text: Home
      - text: "Group 10"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    page-layout: full

editor: visual

